# hi

title: ksk/blog
description: >- # this means to ignore newlines until "baseurl:"
  Personal blog & Fumohouse updates
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://kyoseki.github.io" # the base hostname & protocol for your site, e.g. http://example.com

socials:
  email: hi+blog@voidedxd.xyz
  github: kyoseki
  discord-invite: X8Z3WzA6m6

# Build settings
plugins:
  - jekyll-feed
  - jekyll-paginate

paginate: 5
paginate_path: "/page/:num"

defaults:
  - scope:
      path: ""
      type: "posts"
    values:
      layout: "page"
# Exclude from processing.
# The following items will not be processed, by default.
# Any item listed under the `exclude:` key here will be automatically added to
# the internal "default list".
#
# Excluded items can be processed by explicitly listing the directories or
# their entries' file path in the `include:` list.
#
# exclude:
#   - .sass-cache/
#   - .jekyll-cache/
#   - gemfiles/
#   - Gemfile
#   - Gemfile.lock
#   - node_modules/
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/
